#the public IP of the nodes
ips:
  node0: 0.0.0.0
  node1: 0.0.0.0
  node2: 0.0.0.0
  node3: 0.0.0.0


#the P2P transport port that each node listens on for communication with other nodes
peers_p2p_port:
  node0: 9000
  node1: 9200
  node2: 9400
  node3: 9600

#the port on which the node listens for client requests
rpc_listen_port: 9500
#the number of client commands that should be batched together in a block
batchSize: 1000
#the rate at which the leader produces a block, in milliseconds
batchtimeout: 200
autoviewchange: 0
viewChangetimeout: 5000
lastnewvewtimeout: 5000
checkpoint_t: 10
log_k: 20
maxpool: 3


bgnum: 0
processcount: 1

sim_latency: 10