#the public IP of the nodes
ips:
  node0: 0.0.0.0
  node1: 0.0.0.0
  node2: 0.0.0.0
  node3: 0.0.0.0


#the P2P transport port that each node listens on for communication with other nodes
peers_p2p_port:
  node0: 9000
  node1: 9200
  node2: 9400
  node3: 9600

#the port on which the node listens for client requests
rpc_listen_port: 9500
#the number of client commands that should be batched together in a block
batchSize: 1000
#the rate at which the leader produces a block, in milliseconds
batchtimeout: 8
autoviewchange: 0
viewChangetimeout: 5000
lastnewvewtimeout: 5000
checkpoint_t: 10
log_k: 20
maxpool: 3


bgnum: 0
processcount: 2

sim_latency: 

  node0: 12.90003439
  node1: 50.81495819
  node2: 78.43729271
  node3: 128.2671843
  node4: 317.2057826
  node5: 721.6515553
  node6: 1197.683285


latency_mean: 500
