- hosts: remote
  remote_user: hh
  tasks:
    - name: copy trebiz
      copy:
        src: /home/kuokhane/shareWithPC/code/go/trebiz
        dest: /home/fastpath1/trebiz{{inventory_hostname}}/trebiz{{item}}
      become: yes
      loop: [0]
      loop_control:
        loop_var: item


    - name: chmod trebiz
      shell: chmod +x /home/fastpath1/trebiz{{inventory_hostname}}/trebiz{{item}}/trebiz/trebiz
      become: yes
      loop: [0]
      loop_control:
        loop_var: item

    - name: copy configuration file
      copy:
        src: /home/kuokhane/shareWithPC/code/go/trebiz/config_gen/{{inventory_hostname}}_{{item}}.yaml
        dest: /home/fastpath1/trebiz{{inventory_hostname}}/trebiz{{item}}/trebiz/config.yaml
      become: yes
      loop: [0]
      loop_control:
        loop_var: item
