- hosts: remote
  remote_user: kuokhane
  tasks:
    - name: copy configuration file
      copy:
        src: /home/kuokhane/shareWithPC/code/go/trebiz/config_gen/{{inventory_hostname}}_{{item}}.yaml
        dest: /home/fastpath2/trebiz{{inventory_hostname}}/trebiz{{item}}/trebiz/config.yaml
      become: yes
      loop: [0, 1]
      loop_control:
        loop_var: item
      ignore_errors: yes
